services:
  node:
    build:
      context: ./
      dockerfile: ./.docker/node/Dockerfile
    volumes:
      - ./node_app:/app:cached
    ports:
      - "3000:3000"
    tty: true

  bun:
    build:
      context: ./
      dockerfile: ./.docker/bun/Dockerfile
    volumes:
      - ./bun_app:/app:cached
    ports:
      - "3001:3000"
    tty: true
